### ISSUE TITLE
release.py: Updating NEWS file fails with SSL error

### ISSUE THREAD

**Issue by teg** [osbuild/maintainer-tools#15]
```
teg@tgunders-mac osbuild % python3 ../maintainer-tools/release.py 
Info: You are already on a release branch: release-32
Info: Using token from '$GITHUB_TOKEN'
Info: Updating branch 'release-32' to avoid conflicts...

Release:
  Component:     osbuild
  Version:       32
  Base branch:   release-32
GitHub:
  User:          teg
  Token:         True
  Remote:        teg

Step: Update the NEWS.md file [y/s/N] y
Step: Update NEWS.md with pull request summaries for milestone 32 [y/s/N] y
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)
```

**Comment by teg** [comment]
This was an macOS specific bug, which should be solved by
`/Applications/Python\ 3.9/Install\ Certificates.command` (or equivalent). Thanks @ochosi!
